title: Potteries Hackspace
description: The Potteries Hackspace website.
email: admin@potterieshackspace.org
baseurl: /
url: "http://potterieshackspace.github.io"
favicon: /favicon.png
feedburner_username:
twitter_username: potterieshacks
github_username:  PotteriesHackspace
google_analytics_id: UA-37712920-1
gplus_username: PotteriesHackspace
fb_username: potterieshackspace
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
disqus_short_name: potterieshackspace
disqus_show_comment_count: true
authors:
  jpswade:
    display_name: James Wade
    email: jpswade@gmail.com
    fb: jpswade
    linkedin: jpswade
    twitter: jpswade
    github: jpswade
